@startuml

title __UI's Class Diagram__\n

  namespace com.atf.ui {
    class com.atf.ui.JsHelper {
        {static} + LOGGER : Logger
        {static} + separator : String
        # classlogger : Logger
        ~ actions : Actions
        ~ driver : WebDriver
        ~ js : JavascriptExecutor
        ~ wait : WebDriverWait
        + JsHelper()
        + JsHelper()
        + KeyStrokes()
        + executeJavascript()
        + executeJavascriptAndReturnInteger()
        + executeJavascriptAndReturnString()
        + getCounterErrorValue()
        + iAmMeditating()
        + isJqueryActive()
        + isJqueryLoaded()
        + jqueryClick()
        + jqueryFill()
        + jqueryGetText()
        + jqueryGetTextIgnoringChildElement()
        + jqueryMouseOver()
        + jsControlKeyPlusClick()
        + jsMouseOver()
        + jsScrollIntoView()
        + navigateToPage()
        + refresh()
        + setDriver()
        + setImplicitWait()
        + waitTillElementInDomAndIsVisible()
        + waitTillElementVisible()
        + waitTillElementsToBeVisibleWithText()
        + waitTillVisible()
        - nullifyImplicitWait()
        - resetImplicitWait()
        - waitAndPollForJqueryToBePresent()
    }
  }
  

  namespace com.atf.ui {
    class com.atf.ui.RetryTillPass {
        {static} - LOGGER : Logger
        - c : Class
        + RetryTillPass()
        {static} + main()
        + waitForCodeToPass()
        + waitForCodeToPassUtil()
        - getElapsedTime()
        - invokeMethod()
    }
  }
  

  namespace com.atf.ui {
    class com.atf.ui.UiBase {
        {static} + LOGGER : Logger
        {static} - OS : String
        - isUI : boolean
        + alertCancel()
        + alertOk()
        + awaitAndClick()
        + awaitForElementEnabled()
        + awaitForElementPresence()
        + awaitForElementPresence()
        + awaitForElementPresenceWithMinTimeout()
        + awaitForPageToLoad()
        + checkDynamicBannerForString()
        + clearAllCookies()
        + click()
        + clickAndWaitForPageToLoad()
        + clickAndWaitForPageToLoadBE()
        + clickIfDisplayedElement()
        + clickOnDisplayedElement()
        + clickOnDisplayedWebElementSelenium()
        + clickWithLinkText()
        + convertDateToString()
        + doesPageContainString()
        + doesPageContainStringWithoutWait()
        + enterTextValue()
        + enterTextValueAfterClear()
        + enterTextValueAfterClearSelenium()
        + enterTextValueWebElementSelenium()
        + executeJavaScript()
        + getAlertText()
        + getAttributeText()
        + getButtonUrl()
        + getCssLocator()
        + getCssLocatorFromId()
        + getCurrentUrl()
        + getDisplayedElement()
        + getHref()
        + getName()
        + getOnlyDateFromMillies()
        + getOnlyDateFromMillies()
        + getStyle()
        + getText()
        + getTimeFromMillies()
        + gotoURL()
        + gotoURLSelenium()
        + hoverAndClick()
        + isAlertPresent()
        + isElementDisplayed()
        + isElementDisplayedSelenium()
        + isElementDisplayedWithoutDefaultWait()
        + isElementDisplayedWithoutDefaultWaitSelenium()
        + isElementExists()
        + isSelected()
        + isUI()
        + mouseOverOnElementSelenium()
        + openAndSwitchToNewTabUsingAnyLinkOnPage()
        + openNewTab()
        + refreshPage()
        + setIsUI()
        + switchToAnyLaunchedBrowserTab()
        + switchToNewlyLaunchedBrowserTab()
        + switchToNewlyLaunchedBrowserTabIfAvailable()
        + switchToNewlyLaunchedBrowserTabWithoutClosingExistingTab()
        + verifyElementNotPresent()
        + verifyElementNotPresentWithTimeOutAs()
        + waitForCssElementToBeClickable()
        + waitForElementToBeDisplayed()
        + waitForElementToBeDisplayed()
        + waitForElementToBeDisplayedWebElementSelenium()
        + waitForElementToDisappear()
        + waitForElementToDisappear()
        + waitForPageToLoad()
        + waitForPageToLoadWithRefresh()
        + waitForUrlToContainString()
        - nullifyImplicitWait()
        - resetImplicitWait()
        - setImplicitWait()
        - waitAndPollForElementDisappearance()
        - waitAndPollForElementDisappearance()
        - waitAndPollForElementToBeDisplayed()
        - waitAndPollForElementToBeDisplayed()
    }
  }
  

  com.atf.ui.UiBase -up-|> org.fluentlenium.core.FluentPage


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
