@startuml

title __UTILS's Class Diagram__\n

  namespace com.atf.utils {
    class com.atf.utils.APIConfigReader {
        {static} # logger : Logger
        {static} - BJN_BASELOCATION : String
        {static} - propertyProvider : PropertyProvider
        + APIConfigReader()
        + APIConfigReader()
        + getValue()
        + getValues()
        + updateProperties()
    }
  }
  

  namespace com.atf.utils {
    class com.atf.utils.APIUtils {
        {static} ~ apiConfig : APIConfigReader
        {static} ~ logger : Logger
        {static} + DELETE()
        {static} + DELETE()
        {static} + DELETE_Billing()
        {static} + DELETE_WithBody()
        {static} + GET()
        {static} + GETBasicAuth()
        {static} + GETWithHeader()
        {static} + GET_Password()
        {static} + GET_header()
        {static} + MultipartPOST()
        {static} + MultipartPOSTForFile()
        {static} + MultipartPUT()
        {static} + POST()
        {static} + POST()
        {static} + POSTWithHeader()
        {static} + POSTWithUserNameAndPassword()
        {static} + POST_Without_Body()
        {static} + POST_flexible()
        {static} + POST_header()
        {static} + POST_with_formParameter()
        {static} + POST_with_header()
        {static} + POST_with_message()
        {static} + PUT()
        {static} + PUT()
        {static} + PUT()
        {static} + PUT_WHITOUT_RESPONSE()
        {static} + PUT_Without_Body()
        {static} + PUT_Without_Body_NoResponse()
        {static} + PUT_header()
        {static} + PUT_with_message()
        {static} + cookieEnabledPOST_Without_Body()
        {static} + cookienEnabledPOST()
        {static} + getJson()
        {static} + getJsonArray()
    }
  }
  

  namespace com.atf.utils {
    class com.atf.utils.DBAccess {
        {static} # logger : Logger
        {static} - connection : Connection
        - databaseURL : String
        {static} - instance : DBAccess
        - mySQLDB : String
        - mySQLDBPwd : String
        - mySQLDBUser : String
        - mySQLDatabaseIP : String
        - mySQLDatabasePort : String
        + closeConnection()
        + deleteQuery()
        + deleteQuery()
        + executeSQLQuery()
        {static} + getConnection()
        {static} + getInstance()
        {static} + getInstance()
        + getList()
        + getStructuredData()
        + getTable()
        + getvalue()
        + insertQuery()
        + insertQuery()
        {static} + main()
        + selectQuery()
        + selectQuery()
        + updateQuery()
        + updateQuery()
        - DBAccess()
        - DBAccess()
        - setUpConnection()
    }
  }
  

  namespace com.atf.utils {
    class com.atf.utils.DBAccess.Criterion {
        - criteriaOp : String
        - key : String
        - operator : String
        - value : String
        + Criterion()
        + toString()
    }
  }
  

  namespace com.atf.utils {
    class com.atf.utils.DBAccess.KeyValue {
        - key : String
        - value : String
        + KeyValue()
        + toString()
    }
  }
  

  namespace com.atf.utils {
    class com.atf.utils.DateConverterUtil {
        ~ logger : Logger
        + addDaysToCurrentDate()
        + addDaysToCurrentDateWithFormat()
        + addNdaysFromDate()
        + convertDateByMDY()
        + convertDateBySubtractingOneDayFrom()
        + convertDateByYMD()
        + convertDateFormat()
        + convertDateToCompleteFormat()
        + convertDateToFormat()
        + convertDateToSeconds()
        + convertMarketoDateToNormalDate()
        + convertMarketoSignUpDate()
        + convertStringToDate()
        + covertDatetoEpochForDefaultTimezone()
        + currentDateInIST()
        + currentDatePST()
        + epochToDateConvertor()
        + epochToOnlyDateConvertor()
        + epochToOnlyDateConvertorIST()
        + epochToOnlyDateConvertorInMDYFormat()
        + generateRandomPlanEndDate()
        + reduceTimeByNHours()
        + reduceTimeByNHoursDifferentFormat()
        + subtractNdaysFromDate()
        + subtractNdaysFromDateFormat2()
        + subtractNdaysFromDateWithDifferentFormat()
        + todayDateInPSTFormat()
        + todayDateInPSTFormat()
        + todayDateInPSTFormatpattern()
        + todayDateInPSTFormatpattern1()
    }
  }
  

  namespace com.atf.utils {
    class com.atf.utils.ExcelDataProvider {
        {static} + LOGGER : Logger
        + getTableArray()
        + getTableArrayWithColumnHeaders()
    }
  }
  

  namespace com.atf.utils {
    class com.atf.utils.FileHandler {
        {static} + deleteFileorDirectory()
        {static} + returnFiles()
    }
  }
  

  namespace com.atf.utils {
    class com.atf.utils.PropertyProvider {
        {static} # logger : Logger
        - dictionary : Properties
        + PropertyProvider()
        + getProperty()
        {static} + main()
        + setProperty()
    }
  }
  

  namespace com.atf.utils {
    class com.atf.utils.UiConfigReader {
        {static} # logger : Logger
        {static} - BJN_BASELOCATION : String
        {static} - propertyProvider : PropertyProvider
        + UiConfigReader()
        + UiConfigReader()
        + getValue()
        + getValues()
        + updateProperties()
    }
  }
  

  com.atf.utils.DBAccess o-- com.atf.utils.APIConfigReader : apiConfig
  com.atf.utils.DBAccess +-down- com.atf.utils.DBAccess.Criterion
  com.atf.utils.DBAccess +-down- com.atf.utils.DBAccess.KeyValue


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
