@startuml

title __CONFIG's Class Diagram__\n

  namespace com.atf.config {
    class com.atf.config.APIConfig {
        {static} + BASE_URL : String
        {static} + DB_DRIVER : String
        {static} + DB_ENDPOINT : String
        {static} + DB_PASSWORD : String
        {static} + DB_PORT : String
        {static} + DB_USER : String
        {static} + Password : String
        {static} + Port : String
        {static} + UserName : String
        {static} + logger : Logger
        {static} - conf : ConfigReader
        {static} + getBaseUrl()
        {static} + getDbEndpoint()
        {static} + getDbPassword()
        {static} + getDbPort()
        {static} + getDbUser()
        {static} + getPassword()
        {static} + getPort()
        {static} + getUserName()
        # APIConfig()
        {static} - getProperties()
    }
  }
  

  namespace com.atf.config {
    abstract class com.atf.config.BrowserConfig {
        {static} + BROWSER_PROPERTIES : String
        {static} + BROWSER_TYPE : String
        {static} + DIM_X : String
        {static} + DIM_Y : String
        {static} + ELEMENT_MAX_TIMEOUT : String
        {static} + ELEMENT_MIN_TIMEOUT : String
        {static} + HIGH_DIM_X : String
        {static} + HIGH_DIM_Y : String
        {static} + LOW_DIM_X : String
        {static} + LOW_DIM_Y : String
        {static} + MEDIUM_DIM_X : String
        {static} + MEDIUM_DIM_Y : String
        {static} + PAGELOAD_MAX_TIMEOUT : String
        {static} + URL : String
        {static} + email : String
        {static} + logger : Logger
        {static} + password : String
        {static} + username : String
        {static} - conf : ConfigReader
        {static} + getBrowserProperties()
        {static} + getBrowserType()
        {static} + getDimX()
        {static} + getDimY()
        {static} + getElementMaxTimeout()
        {static} + getElementMinTimeout()
        {static} + getEmail()
        {static} + getHighDimX()
        {static} + getHighDimY()
        {static} + getLowDimX()
        {static} + getLowDimY()
        {static} + getMediumDimX()
        {static} + getMediumDimY()
        {static} + getPageLoadMaxTimeOut()
        {static} + getPassword()
        {static} + getUrl()
        {static} + getUsername()
        # BrowserConfig()
        {static} - getProperties()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
