@startuml

title __CONFIG's Class Diagram__\n

  namespace com.atf.config {
    class com.atf.config.APIConfig {
    }
  }
  

  namespace com.atf.config {
    abstract class com.atf.config.BrowserConfig {
        {static} + BROWSER_PROPERTIES : String
        {static} + BROWSER_TYPE : String
        {static} + DIM_X : String
        {static} + DIM_Y : String
        {static} + ELEMENT_MAX_TIMEOUT : String
        {static} + ELEMENT_MIN_TIMEOUT : String
        {static} + ENV_PROP : String
        {static} + HIGH_DIM_X : String
        {static} + HIGH_DIM_Y : String
        {static} + HUB_URL : String
        {static} + HUB_URL_MULTIMONITOR : String
        {static} + LOGGER : Logger
        {static} + LOW_DIM_X : String
        {static} + LOW_DIM_Y : String
        {static} + MEDIUM_DIM_X : String
        {static} + MEDIUM_DIM_Y : String
        {static} + PAGELOAD_MAX_TIMEOUT : String
        {static} + TEST_TAG : String
        {static} + email : String
        {static} + moderator_passcode : String
        {static} + participant_passcode : String
        {static} + password : String
        {static} + separator : String
        {static} + username : String
        {static} - CARMEL_IP : String
        {static} - MODERATOR_BROWSER_IP : String
        {static} - MODERATOR_BROWSER_TYPE : String
        {static} - PARTICIPANT_BROWSER_IP : String
        {static} - PARTICIPANT_BROWSER_TYPE : String
        {static} - SECURITY_ENABLE_PROXY : String
        {static} - SECURITY_PROXY_PORT : String
        {static} - SECURITY_PROXY_SERVER : String
        {static} - SKINNY_BROWSER_IP : String
        {static} - WEBRTC_BROWSER_IP : String
        {static} - props : Properties
        {static} - resourceFile : String
        {static} + getBrowserProperties()
        {static} + getBrowserType()
        {static} + getCarmelIP()
        {static} + getDimX()
        {static} + getDimY()
        {static} + getElementMaxTimeout()
        {static} + getElementMinTimeout()
        {static} + getEnvProp()
        {static} + getHighDimX()
        {static} + getHighDimY()
        {static} + getHubURL()
        {static} + getHubURLForMultiMonitor()
        {static} + getLowDimX()
        {static} + getLowDimY()
        {static} + getMediumDimX()
        {static} + getMediumDimY()
        {static} + getModerator_BrowserIP()
        {static} + getModerator_BrowserType()
        {static} + getPageLoadMaxTimeOut()
        {static} + getParticipant_BrowserIP()
        {static} + getParticipant_BrowserType()
        {static} + getSecurityEnableStatus()
        {static} + getSecurityProxyServerIP()
        {static} + getSecurityProxyServerPort()
        {static} + getSkinny_BrowserIP()
        {static} + getTestTags()
        {static} + getWebrtc_BrowserIP()
        {static} + loadGradleResource()
        # BrowserConfig()
        {static} - getProperties()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
